function [F,V,Xdot] = linearizedModel1(bgx,dt,nbgx,nbgy,nbgz,ngx,ngy,ngz,nvx,nvy,nvz,phi,theta,vx,vy,vz,wx,wy,wz)
%LINEARIZEDMODEL1
%    [F,V,XDOT] = LINEARIZEDMODEL1(BGX,DT,NBGX,NBGY,NBGZ,NGX,NGY,NGZ,NVX,NVY,NVZ,PHI,THETA,VX,VY,VZ,WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Apr-2019 14:40:30

t2 = cos(theta);
t3 = sin(theta);
t4 = bgx.*t2;
t5 = ngz.*t2;
t6 = t3.*wx;
t12 = bgx.*t3;
t13 = t2.*wz;
t14 = ngx.*t3;
t7 = t4+t5+t6-t12-t13-t14;
t8 = cos(phi);
t9 = sin(phi);
t10 = 1.0./t8;
t11 = 1.0./t8.^2;
t15 = sqrt(2.0);
t16 = pi.*(1.0./4.0);
t17 = t16+theta;
F = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,dt.*t7.*t11,-dt.*t7.*t9.*t11,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t7,-t10.*(-t8+bgx.*dt.*t2.*t9+bgx.*dt.*t3.*t9+dt.*ngx.*t2.*t9+dt.*ngz.*t3.*t9-dt.*t2.*t9.*wx-dt.*t3.*t9.*wz),dt.*t10.*(t4+t12+ngx.*t2+ngz.*t3-t2.*wx-t3.*wz),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t15.*sin(t17),-dt.*t10.*(t8-t2.*t9+t3.*t9),-dt.*t10.*t15.*cos(t17),1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[9,9]);
if nargout > 1
    V = reshape([-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2,-t3.*t9.*t10,t3.*t10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3,t2.*t9.*t10,-t2.*t10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[9,9]);
end
if nargout > 2
    t18 = t2.^2;
    t19 = t3.^2;
    t20 = t18+t19;
    t21 = 1.0./t20;
    t22 = bgx+ngz-wz;
    t23 = t8.*t18;
    t24 = t8.*t19;
    t25 = t23+t24;
    t26 = 1.0./t25;
    t27 = bgx+ngx-wx;
    Xdot = [-nvx+vx;-nvy+vy;-nvz+vz;-t3.*t21.*t22-t2.*t21.*t27;-bgx-ngy+wy+t2.*t9.*t22.*t26-t3.*t9.*t26.*t27;-t2.*t22.*t26+t3.*t26.*t27;nbgx;nbgy;nbgz];
end
