function [F,V,Xdot] = getParameters1(in1,in2,in3,dt)
%GETPARAMETERS1
%    [F,V,XDOT] = GETPARAMETERS1(IN1,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    14-Apr-2019 10:25:04

bgx = in1(7,:);
nbgx = in3(7,:);
nbgy = in3(8,:);
nbgz = in3(9,:);
ngx = in3(4,:);
ngy = in3(5,:);
ngz = in3(6,:);
nvx = in3(1,:);
nvy = in3(2,:);
nvz = in3(3,:);
phi = in1(4,:);
theta = in1(5,:);
vx = in2(1,:);
vy = in2(2,:);
vz = in2(3,:);
wx = in2(4,:);
wy = in2(5,:);
wz = in2(6,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = bgx.*t2;
t5 = ngz.*t2;
t6 = t3.*wx;
t12 = bgx.*t3;
t13 = t2.*wz;
t14 = ngx.*t3;
t7 = t4+t5+t6-t12-t13-t14;
t8 = cos(phi);
t9 = sin(phi);
t10 = 1.0./t8;
t11 = 1.0./t8.^2;
t15 = sqrt(2.0);
t16 = pi./4.0;
t17 = t16+theta;
t18 = ngx.*t2;
t19 = ngz.*t3;
t20 = t4+t12+t18+t19-t2.*wx-t3.*wz;
F = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,dt.*t7.*t11,-dt.*t7.*t9.*t11,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t7,-t10.*(-t8+bgx.*dt.*t2.*t9+bgx.*dt.*t3.*t9+dt.*ngx.*t2.*t9+dt.*ngz.*t3.*t9-dt.*t2.*t9.*wx-dt.*t3.*t9.*wz),dt.*t10.*t20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t15.*sin(t17),-dt.*t10.*(t8-t2.*t9+t3.*t9),-dt.*t10.*t15.*cos(t17),1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[9,9]);
if nargout > 1
    V = reshape([-dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t2,-dt.*t3.*t9.*t10,dt.*t3.*t10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-dt.*t3,dt.*t2.*t9.*t10,-dt.*t2.*t10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dt],[9,9]);
end
if nargout > 2
    t21 = t2.^2;
    t22 = t3.^2;
    t23 = t21+t22;
    t24 = 1.0./t23;
    Xdot = [-nvx+vx;-nvy+vy;-nvz+vz;-t20.*t24;-t10.*t24.*(-bgx.*t2.*t9+bgx.*t3.*t9+bgx.*t8.*t21+bgx.*t8.*t22+ngx.*t3.*t9+ngy.*t8.*t21+ngy.*t8.*t22-ngz.*t2.*t9-t3.*t9.*wx-t8.*t21.*wy-t8.*t22.*wy+t2.*t9.*wz);-t7.*t10.*t24;nbgx;nbgy;nbgz];
end
